backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "tools_english"
    label: "Tools (English)"
    folder: "content/tools/en"
    create: true
    format: "frontmatter"
    slug: "{{number}}-{{slug}}"
    fields:
      - {
          label: "Tool Number",
          name: "number",
          widget: "number",
          value_type: "int",
        }
      - { label: "Name", name: "name", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          hint: "Upload or select an image for this tool.",
        }
      - { label: "Summary", name: "summary", widget: "text", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Outcomes", name: "outcomes", widget: "text", required: true }
      - {
          label: "Instructions",
          name: "instructions",
          widget: "text",
          required: true,
        }
      - { label: "Benefits", name: "benefits", widget: "text", required: true }
      - { label: "Purpose", name: "purpose", widget: "string", required: true }
      - {
          label: "Prerequisite Tools",
          name: "prerequisiteTools",
          widget: "text",
        }
      - {
          label: "Partner",
          name: "partner",
          widget: "select",
          options: ["ACEEU", "EUEI", "TVW", "MMS", "UNEAT", "MC"],
        }
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  - name: "tools_spanish"
    label: "Tools (Spanish)"
    folder: "content/tools/es"
    create: true
    format: "frontmatter"
    slug: "{{number}}-{{slug}}"
    fields:
      - {
          label: "Tool Number",
          name: "number",
          widget: "number",
          value_type: "int",
        }
      - { label: "Name", name: "name", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          hint: "Upload or select an image for this tool.",
        }
      - { label: "Summary", name: "summary", widget: "text", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Outcomes", name: "outcomes", widget: "text", required: true }
      - {
          label: "Instructions",
          name: "instructions",
          widget: "text",
          required: true,
        }
      - { label: "Benefits", name: "benefits", widget: "text", required: true }
      - { label: "Purpose", name: "purpose", widget: "string", required: true }
      - {
          label: "Prerequisite Tools",
          name: "prerequisiteTools",
          widget: "text",
        }
      - {
          label: "Partner",
          name: "partner",
          widget: "select",
          options: ["ACEEU", "EUEI", "TVW", "MMS", "UNEAT", "MC"],
        }
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  - name: "tools_german"
    label: "Tools (German)"
    folder: "content/tools/de"
    create: true
    format: "frontmatter"
    slug: "{{number}}-{{slug}}"
    fields:
      - {
          label: "Tool Number",
          name: "number",
          widget: "number",
          value_type: "int",
        }
      - { label: "Name", name: "name", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          hint: "Upload or select an image for this tool.",
        }
      - { label: "Summary", name: "summary", widget: "text", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Outcomes", name: "outcomes", widget: "text", required: true }
      - {
          label: "Instructions",
          name: "instructions",
          widget: "text",
          required: true,
        }
      - { label: "Benefits", name: "benefits", widget: "text", required: true }
      - { label: "Purpose", name: "purpose", widget: "string", required: true }
      - {
          label: "Prerequisite Tools",
          name: "prerequisiteTools",
          widget: "text",
        }
      - {
          label: "Partner",
          name: "partner",
          widget: "select",
          options: ["ACEEU", "EUEI", "TVW", "MMS", "UNEAT", "MC"],
        }
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  - name: "tools_greek"
    label: "Tools (Greek)"
    folder: "content/tools/el"
    create: true
    format: "frontmatter"
    slug: "{{number}}-{{slug}}"
    fields:
      - {
          label: "Tool Number",
          name: "number",
          widget: "number",
          value_type: "int",
        }
      - { label: "Name", name: "name", widget: "string", required: true }
      - {
          label: "Image",
          name: "image",
          widget: "image",
          required: true,
          hint: "Upload or select an image for this tool.",
        }
      - { label: "Summary", name: "summary", widget: "text", required: true }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Outcomes", name: "outcomes", widget: "text", required: true }
      - {
          label: "Instructions",
          name: "instructions",
          widget: "text",
          required: true,
        }
      - { label: "Benefits", name: "benefits", widget: "text", required: true }
      - { label: "Purpose", name: "purpose", widget: "string", required: true }
      - {
          label: "Prerequisite Tools",
          name: "prerequisiteTools",
          widget: "text",
        }
      - {
          label: "Partner",
          name: "partner",
          widget: "select",
          options: ["ACEEU", "EUEI", "TVW", "MMS", "UNEAT", "MC"],
        }
      - label: "Links"
        name: "links"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
